version: "3.9"
services:
  dumpster-microservice:
    image: "ghcr.io/smartwastecollection/dumpster-microservice:v1.1.0"
    env_file:
        - .env
    ports:
      - "3000:8080"
    networks:
      - swc-net

  truck-microservice:
    image: "ghcr.io/smartwastecollection/truck-microservice:v0.2.10"
    env_file:
        - .env
    environment:
        - server.port=8080
    ports:
        - "3001:8080"
    networks:
      - swc-net

  booking-microservice:
    image: "ghcr.io/smartwastecollection/booking-microservice:v0.2.0"
    env_file:
        - .booking-ms.env
    environment:
        - SERVER_PORT=3000
    ports:
        - "3002:3000"
    networks:
      - swc-net

  complaint-microservice:
    image: "ghcr.io/smartwastecollection/complaint-microservice:v1.0.10"
    env_file:
        - .complaint-mission-ms.env
    ports:
        - "3003:8080"
    networks:
      - swc-net

  mission-microservice:
    image: "ghcr.io/smartwastecollection/mission-microservice:v0.1.8"
    env_file:
        - .env
        - .complaint-mission-ms.env
    environment:
        - DUMPSTER_ADDRESS=http://dumpster-microservice:8080/dumpsters/
        - BOOKING_ADDRES=http://booking-microservice:8080/bookings/
    ports:
        - "3004:8080"
    networks:
      - swc-net

  authentication-microservice:
    image: "ghcr.io/smartwastecollection/authentication-microservice:v0.0.2"
    env_file:
      - .authentication-ms.env
    ports:
      - "3005:3002"
    networks:
      - swc-net

  dashboard:
    image: "ghcr.io/smartwastecollection/dashboard:v0.1.0"
    env_file:
      - .dashboard.env
    ports:
      - "8080:8080"
    networks:
      - swc-net

networks:
  swc-net:
